version: 0.2

env:
  variables:
    JAVA_HOME: /usr/lib/jvm/java-21-amazon-corretto
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing SAM CLI..."
      - pip3 install aws-sam-cli
      - sam --version

  pre_build:
    commands:
      - echo "Running tests..."
      - cd ServerlessFunction
      - chmod +x gradlew
      - ./gradlew clean test
      - echo "Tests completed"

  build:
    commands:
      - echo "Building SAM application..."
      - cd $CODEBUILD_SRC_DIR/ServerlessFunction
      - sam build
      - echo "Packaging SAM application..."
      - sam package \
          --s3-bucket ${ARTIFACT_BUCKET} \
          --s3-prefix sam-packages \
          --output-template-file packaged-template.yaml

  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - packaged-template.yaml
  base-directory: ServerlessFunction

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'

reports:
  junit-reports:
    files:
      - 'ServerlessFunction/build/test-results/test/*.xml'
    file-format: JUNITXML
  jacoco-reports:
    files:
      - 'ServerlessFunction/build/reports/jacoco/test/jacocoTestReport.xml'
    file-format: JACOCOXML
