AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Group2 English Study - Vocabulary Domain

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: java21
    Architectures:
      - x86_64
    Environment:
      Variables:
        VOCAB_TABLE_NAME: !Ref VocabTable
        VOCAB_BUCKET_NAME: group2-englishstudy
        AWS_REGION_NAME: !Ref AWS::Region

Resources:
  #############################################
  # Lambda Functions
  #############################################

  # 단어 관리 함수
  WordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: group2-englishstudy-vocab-word-handler
      CodeUri: VocabFunction
      Handler: com.mzc.secondproject.serverless.vocabulary.handler.WordHandler::handleRequest
      Description: Handle word CRUD operations
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VocabTable
      Events:
        CreateWord:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/words
            Method: POST
        GetWords:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/words
            Method: GET
        GetWord:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/words/{wordId}
            Method: GET
        UpdateWord:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/words/{wordId}
            Method: PUT
        DeleteWord:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/words/{wordId}
            Method: DELETE

  # 사용자 단어 학습 상태 관리 함수
  UserWordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: group2-englishstudy-vocab-userword-handler
      CodeUri: VocabFunction
      Handler: com.mzc.secondproject.serverless.vocabulary.handler.UserWordHandler::handleRequest
      Description: Handle user word learning status
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VocabTable
      Events:
        GetUserWords:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/users/{userId}/words
            Method: GET
        GetUserWord:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/users/{userId}/words/{wordId}
            Method: GET
        UpdateUserWord:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/users/{userId}/words/{wordId}
            Method: PUT

  # 일일 학습 관리 함수 (55개 단어 할당)
  DailyStudyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: group2-englishstudy-vocab-daily-handler
      CodeUri: VocabFunction
      Handler: com.mzc.secondproject.serverless.vocabulary.handler.DailyStudyHandler::handleRequest
      Description: Handle daily study word assignment
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VocabTable
      Events:
        GetDailyWords:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/daily/{userId}
            Method: GET
        MarkWordLearned:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/daily/{userId}/words/{wordId}/learned
            Method: POST

  # 시험 기능 함수
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: group2-englishstudy-vocab-test-handler
      CodeUri: VocabFunction
      Handler: com.mzc.secondproject.serverless.vocabulary.handler.TestHandler::handleRequest
      Description: Handle vocabulary tests
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VocabTable
      Events:
        StartTest:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/test/{userId}/start
            Method: POST
        SubmitAnswer:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/test/{userId}/submit
            Method: POST
        GetTestResult:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/test/{userId}/results
            Method: GET

  # 통계 함수
  StatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: group2-englishstudy-vocab-stats-handler
      CodeUri: VocabFunction
      Handler: com.mzc.secondproject.serverless.vocabulary.handler.StatsHandler::handleRequest
      Description: Handle user learning statistics
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VocabTable
      Events:
        GetStats:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/stats/{userId}
            Method: GET
        GetDailyStats:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/stats/{userId}/daily
            Method: GET

  # 음성 변환 함수 (Polly)
  VoiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: group2-englishstudy-vocab-voice-handler
      CodeUri: VocabFunction
      Handler: com.mzc.secondproject.serverless.vocabulary.handler.VoiceHandler::handleRequest
      Description: Convert word to speech using Polly
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VocabTable
        - S3CrudPolicy:
            BucketName: group2-englishstudy
        - Statement:
            - Effect: Allow
              Action:
                - polly:SynthesizeSpeech
                - polly:DescribeVoices
              Resource: "*"
      Events:
        TextToSpeech:
          Type: Api
          Properties:
            RestApiId: !Ref VocabApi
            Path: /vocab/voice/synthesize
            Method: POST

  #############################################
  # API Gateway
  #############################################

  VocabApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: group2-englishstudy-vocab-api
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key'"
        AllowOrigin: "'*'"

  #############################################
  # DynamoDB
  #############################################

  VocabTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: group2-englishstudy-vocab
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

#############################################
# Outputs
#############################################

Outputs:
  VocabApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${VocabApi}.execute-api.${AWS::Region}.amazonaws.com/dev/'

  VocabTableName:
    Description: DynamoDB Table Name
    Value: !Ref VocabTable

  WordFunctionArn:
    Description: Word Lambda Function ARN
    Value: !GetAtt WordFunction.Arn

  UserWordFunctionArn:
    Description: UserWord Lambda Function ARN
    Value: !GetAtt UserWordFunction.Arn

  DailyStudyFunctionArn:
    Description: DailyStudy Lambda Function ARN
    Value: !GetAtt DailyStudyFunction.Arn

  TestFunctionArn:
    Description: Test Lambda Function ARN
    Value: !GetAtt TestFunction.Arn

  StatsFunctionArn:
    Description: Stats Lambda Function ARN
    Value: !GetAtt StatsFunction.Arn

  VoiceFunctionArn:
    Description: Voice Lambda Function ARN
    Value: !GetAtt VoiceFunction.Arn
